### PR TITLE
- fix a bug with Slice() where it deletes all dimensions of size 1.

### LINKED ISSUE #30: Slice bug "drop any dimension with size 1"
https://github.com/gorgonia/gorgonia/issues/208

@matdodgson

### PR DESCRIPTION
**Pull request by matdodgson**
fixes #30

### CODE REVIEW

**Comment by chewxy** [comment]
Can you add the specific test cases too? Thanks

**Comment by matdodgson** [comment]
Ok I made the change on AP and Shape and put some automated testing in there.

**Comment by chewxy** [comment]
Thank you for that. 

There seems to be a bit more failures around the special cases of row vectors: job record - https://travis-ci.org/gorgonia/tensor/jobs/384021550#L1289 - the strides are wrong

What do you think the right answer should be @matdodgson 

The numpy equivalent is these:

```
>>> a = np.arange(5).reshape(1,5)
>>> a[:, 0:2].shape
(1, 2)
>>> a[:, 0:2].strides
(40, 8) # the Gorgonia version would be []int{5, 1}
```
Here we run into a bit of a problem.

Let's consider what the correct answer should be:

- Slicing a matrix should yield a matrix.
- Numpy is correct so far.

The answer should be 

```
[
[0, 1]
]
```

If we look at how the data is laid out:

```
[
[0, 1, 2,  3, 4]
]
```

The resulting stride has to be `[]int{5, 1}`.

For the second failure, the same thing happens: The resulting strides should be `[]int{5, 2}`.

Question is why it's not?

**Comment by chewxy** [comment]
I understand chasing down this problem would make large swarths of changes across `tensor` and `gorgonia`.

There were some reasons why I hadn't implemented full numpy compatibility and retained the notion of `rowVec` and `colVec`. That however, has complicated Gorgonia a LOT. I think it may be wise to rethink that notion.

I'd be happy to make all the changes you recommend. Impact would be fairly large, but fuckit, let's do it.

So now the question becomes: do you want to keep chasing this problem?  It might take some time.

**Comment by matdodgson** [comment]
Yeah I see the 1st stride problem {1,1} instead of {5,1}. IsVector() is true which overrides the stride. The 2nd problem has the same cause (IsVector() being true).

I guess that we're talking how to interpret a tensor of shape {1,5}: is it a vector or a matrix? It seems the code assumes this is a vector.

I don't know your code base since I only started using it recently. I'm sure you had good reasons for the IsVector() bit.

**Comment by matdodgson** [comment]
Hi Chewxy!

First of all: yes I'm an Aussie but I'm currently living in Phnom Penh,
so I'm 3 hours behind you!
Let me tell you about my problem: I'm trying to implement a simple but
non standard ML kernel. Because it's non standard there is no simple way
to implement it in tensorflow or pytorch. When I implemented a prototype
in native Python it was of course super slow. I wanted to try to
implement it in a more performant language and I thought I would try
golang. I came across your tensor library and thought I give it a try.
Like you, my free time is very limited. The main focus of my free time
is my (modest) ML research. Regarding a contribution to gorgonia
tensor, I'd be happy to help with smaller changes - the size of the
slice change I worked on. I'm sorry to say that making larger changes -
such as the more fundamental change you're talking about - is not
something I can commit to. I realise my pull request is useless without
the more fundamental changes you mention; I won't feel bad if you
refuse the request.
At this point, I'm either going to work around the problem in your
tensor library, or move to another language such as c++ & cuda (yuck) or
Julialang. I wish you luck with gorgonia and the tensor library and I'm
sorry I couldn't become more involved in it. And I'm also sorry for my
sloppy work: my first commit had no new automated testing; before my
second commit I did not run ALL of the automated tests :-(
--
Mat Dodgson


On Sun, May 27, 2018, at 5:07 AM, Chewxy wrote:
> I understand chasing down this problem would make large swarths of
> changes across tensor and gorgonia.> There were some reasons why I hadn't implemented full numpy
> compatibility and retained the notion of rowVec and colVec. That
> however, has complicated Gorgonia a LOT. I think it may be wise to
> rethink that notion.> I'd be happy to make all the changes you recommend. Impact would be
> fairly large, but fuckit, let's do it.> So now the question becomes: do you want to keep chasing this problem?
> It might take some time.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/gorgonia/tensor/pull/31#issuecomment-392291063

**Comment by chewxy** [comment]
Not a problem dude. What I'm going to do is fix up this issue within the week - vectors etc

**Comment by matdodgson** [comment]
Fantastic - thanks!

On May 28, 2018 4:37:02 AM GMT+07:00, Chewxy <notifications@github.com> wrote:
>Not a problem dude. What I'm going to do is fix up this issue within
>the week - vectors etc
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gorgonia/tensor/pull/31#issuecomment-392377668

-- 
Mat

**Comment by chewxy** [comment]
Are you OK with me rolling this into v0.9.0?

**Comment by matdodgson** [comment]
Sure no problem 😀

On May 30, 2018 7:17:34 AM GMT+07:00, Chewxy <notifications@github.com> wrote:
>Are you OK with me rolling this into v0.9.0?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gorgonia/tensor/pull/31#issuecomment-392990111

-- 
Mat

**Comment by chewxy** [comment]
@matdodgson you haven't pushed your changes with the tests thru...

**Comment by chewxy** [comment]
oops.. my bad..  you did

**Comment by chewxy** [comment]
Closing this since d260042 to cebe4a0 fixes this issue in the upcoming v0.9.0 branch. Thanks @matdodgson

**Comment by wzzhu** [comment]
The problem still exists in v0.9.24.

The root cause seems to be in IsVector()

In slice func, if it is a vector, it will set the outer dimension to 0 instead of the normal outer one.

```
func (ap *AP) S(size int, slices ...Slice) (newAP AP, ndStart, ndEnd int, err error) {
       ...
	if ap.o.IsRowMajor() || ap.IsVector() {
		outerDim = 0
	} else {
		outerDim = len(ap.shape) - 1
	}
...
}
```

In return it calls func (s Shape) IsVector() bool { return s.IsColVec() || s.IsRowVec() || (len(s) == 1) }

It is better that IsVector just check len(s) == 1 instead of converting something like nx1 or 1xn to a vector. Since this checking makes the definition not strict and may cause many unknown bugs for tensors. If needing to squeeze the tensor, should explicitly call. Otherwise a tensor of shape, e.g., (1, 1) should still be treated as a 2-d array instead of vector or scalar.

**Pull request closed without merging**
