### PR TITLE
fix: permute strides

### PR DESCRIPTION
**Pull request by strigi-form**
strides must be permuted for 2d tensors with any dimension == 1

### CODE REVIEW

**Comment by chewxy** [comment]
can you give an example?

**Comment by strigi-form** [comment]
Yes, it is in issue #84, here is a copy/paste
This simple code panics
2020/10/15 13:11:28 (3, 1)
C[-1 %!v(PANIC=Format method: runtime error: index out of range [3] with length 3)

```
package main

import (
"log"

"gorgonia.org/tensor"
)

func main() {
var T tensor.Tensor
T = tensor.New(
tensor.WithShape(1, 3),
tensor.WithBacking([]float64{-1, 0, 1}))
T, _ = tensor.T(T)
log.Printf("%v\n%v\n", T.Shape(), T)
}
```

**Comment by strigi-form** [comment]
The problem is you can't iterate on a transposed *tensor.Dense (tensor.AP in fact) when IsRowVec() is true:
```
it := tensor.IteratorFromDense(t.tens.(*tensor.Dense))
for i, ierr := it.Next(); ierr == nil; i, ierr = it.Next() {
 .....
}
```
First value for i is ok, but next is dimension (or stride which is 3 in my example), so panic out of range

**Comment by chewxy** [comment]
OK analysing

**Comment by chewxy** [comment]
This LGTM. It passes on my local machine. No idea why it fails in travis

**Pull request merged**
