### PR TITLE
Add subdirectories to tested folders in Github workflow

### PR DESCRIPTION
**Pull request by MarkKremer**
I noticed tests aren't executed for subdirectories. So I added them to the Github workflow and fixed the tests in those directories.

Some other tests still fail or timeout but I haven't touched those.

### CODE REVIEW

**Comment by dcu** [comment]
can you fix the test that's broken?

**Comment by MarkKremer** [comment]
I'll have a look but I can't promise I'll be able to fix it. I'm fairly certain that the error wasn't introduced by my PR but it's a race condition or something. [The same test succeeds in my other PR](https://github.com/gorgonia/tensor/pull/109/checks?check_run_id=2210208193) which is branched of of this one. It will be difficult to reproduce.

I'll also have a look at increasing the timeouts. Do you want to have the timeouts increased?

**Comment by dcu** [comment]
it's a good point, the tests in the other PR pass. Increasing the timeout should be fine I think

**Comment by MarkKremer** [comment]
Whoop, all green!

I fixed the [deprecated set-env and add-path](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) in the workflow too.

**Review by dcu — APPROVED** [review]

**Pull request merged**
